### PR TITLE
Support new protocol of completions response

### PR DESCRIPTION
**Pull request by neutralevil**
Completion returns each candidate as a dictionary.

### CODE REVIEW

**Comment by tpope** [comment]
What else is in the dictionary? We can maybe populate it into the menu or preview window.

**Comment by neutralevil** [comment]
Using cider-nrepl "0.9.0-SNAPSHOT", there was only a candidate word in the dictionary yesterday. But the updated snapshot version returns more detailed info, like below:
``` clojure
{:completions
  [{:candidate "find", :ns "clojure.core", :type "function"}
   {:candidate "find-ns", :ns "clojure.core", :type "function"}
   {:candidate "find-doc", :ns "clojure.repl", :type "function"}
   {:candidate "find-var", :ns "clojure.core", :type "function"}
   {:candidate "find-name", :ns "user", :type "function"}
   {:candidate "find-keyword", :ns "clojure.core", :type "function"}
   {:candidate "find-protocol-impl",
    :ns "clojure.core",
    :type "function"}
   {:candidate "find-protocol-method",
    :ns "clojure.core",
    :type "function"}],
  :id "92e4496e-4b9c-4b0b-8a1d-f611f6ef2aa4",
  :status ["done"]})
```

I'll try to make a new patch.

**Comment by tpope** [comment]
If you could add a `"kind"` key containing `get(v:val, 'type', '')[0]` that would be great. I don't see anything else worth grabbing.

**Comment by Deraen** [comment]
This is the same as https://github.com/tpope/vim-fireplace/pull/210

Though it looks like I might have missed some possible candidate types.

**Comment by tpope** [comment]
Forgot about this one. If there are additional types to get a new request would be great.

**Pull request closed without merging**
