### PR TITLE
Completion context

### LINKED ISSUE #212: Support for completion context
Complete operation can be passed context option so that the completion library can give better suggestions. The context should be the surrounding toplevel form with word being completed replaced with word `__prefix__`.

I did already start with this: https://github.com/tpope/vim-fireplace/compare/master...Deraen:completion-context?expand=1
I have the toplevel form yanked to variable but I'm not sure how I can insert the `__prefix__` in correct position. Maybe some magic using current cursor position?
Looks like the yanked string doesn't contain the word being completed.

- complete operation docs: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj#L63
- compliment context docs: https://github.com/alexander-yakushev/compliment/wiki/Context

### PR DESCRIPTION
**Pull request by Deraen**
Fixes #212 

This is still work in progress but I opened this for comments and help.

My current strategy is to first yank from start of toplevel form to cursor and then from cursor to end of the form. Problem is that the latter yank is not working.

### CODE REVIEW

**Comment by Deraen** [comment]
I got this working by yanking the whole toplevel form in one operation and then using strpart to select start and end parts. To find the cursor position I calculate number of characters in yanked text from start of the form to cursor pos.

screenshot

**Comment by tpope** [comment]
You're saving `'selection'` and `'clipboard'` but best I can tell aren't changing them to safe values. If you can manage it, I would rather avoid that dance entirely and use `getline()`. I think [this logic](https://github.com/tpope/vim-fireplace/blob/819438bdf438ce3d4a18d1562a19aa63c5efeb63/plugin/fireplace.vim#L958-964) would work.

**Comment by Deraen** [comment]
Thanks, that works.

Other comments before I start cleaning this?

**Comment by tpope** [comment]
I haven't fully digested the logic but looks good to me. I would favor pulling `s:pos_inside_selection` inline.

**Comment by Deraen** [comment]
Okay should be cleared now.

**Comment by tpope** [comment]
Thanks for figuring this out; I'm excited to try it.

**Pull request merged**
