### PR TITLE
Use cider info op for Find

### PR DESCRIPTION
**Pull request by Deraen**
This adds gf support for Cljs

### CODE REVIEW

**Comment by tpope** [comment]
`gf` is go to file **not** jump to definition. Other than the alias edge case (which in hindsight was probably a mistake), it works statically, not requiring a repl connection at all. Best I can tell, you're greatly expanding the use of a repl connection to solve...what exactly?

**Comment by Deraen** [comment]
To add support for alias edge case in Cljs. I don't know how `gf` should be used but several people where mentioning on Clojurians Slack that `gf` is broken with Cljs. It throws an exception when used on path with alias because it's trying to call `ns-aliases` which doesn't exists on Cljs. This only changes the edge case, which already used repl, to use cider which works for both Clj and Cljs.

**Comment by tpope** [comment]
The `file !~# '\.'` check limits it to alias candidates only. You need to wrap that around the whole thing.

**Comment by tpope** [comment]
While I'm willing to accept a patch if that is addressed, the "broken" allegation is bollocks, as the behavior desired is not covered by the `gf` documentation. This is what `]<C-D>` is for.

**Comment by Deraen** [comment]
Fixed as suggested.

**Pull request closed without merging**
