### PR TITLE
Change :Piggieback behavior for empty/port parameters

### PR DESCRIPTION
**Pull request by siphiuel**
- Use Rhino REPL when no parameters are provided
  - Use Weasel REPL when port parameter is specified

### CODE REVIEW

**Comment by tpope** [comment]
My willingness to support weasel was contingent on checking for its presence and falling back to the old technique if it isn't found.  Verify what `connection.eval("(require 'weasel.repl.websocket)")` returns when weasel is unavailable and key off of that.

**Comment by siphiuel** [comment]
Arrgh, yes, sorry for that. So i did -  if Weasel is in classpath it would return `[['status', ['done']]`, otherwise `[['status', ['eval-error', 'done']]`. Modified the code accordingly.

**Comment by tpope** [comment]
Oh, in that case, `has_key(..., 'ex')` would work too, right? Please use that instead, as it's the pattern I've settled on elsewhere.

**Comment by siphiuel** [comment]
Done. Thanks - this really looks simpler.

**Comment by venantius** [comment]
@siphiuel I pulled down your branch and was able to evaluate forms from a ClojureScript file, woohoo! Was able to verify specifically that it was ClojureScript being passed through the REPL connection by doing:
```
:Eval (cljs.core/conj [] 1)
``` 
which evaluated successfully.

That might be enough alone to warrant this being marked as "good enough", but...for some reason `Doc` doesn't work. Strangely, even trying to do doc within an eval block also fails: 
```
:Eval (doc cljs.core/conj)
``` 
throws the following: 
```
{'status': ['eval-error', 'done'], 'ex': 'class clojure.lang.ExceptionInfo', 'root-ex': 'class clojure.lang.ExceptionInf
o', 'id': 'fireplace-jackalope.local-1443571827-17', 'session': ['49a325bc-2741-459f-a673-24f568e09e4b'], 'err': 'org.mo
zilla.javascript.EvaluatorException: Java class "[Ljava.lang.StackTraceElement;" has no public instance field or method
named "cljs$lang$protocol_mask$partition0$". (rhino.clj#41)^@'}
```
Not sure what the root cause is there, but figured it was worth flagging now while we're working on this.

**Comment by tpope** [comment]
Regarding the second error, is `doc` even available in your namespace?

**Comment by venantius** [comment]
Touche, it was not. `(cljs.repl/doc conj)` works as it should. 

There may still need to be some mapping of `K` to `(cljs.repl/doc)` based on the right filetype (not sure how to handle .cljc/cljx files) -- trying to use `K` on, e.g. `conj` in a `.cljs` file returns documentation on `clojure.core/conj` rather than `cljs.core/conj`.

**Comment by tpope** [comment]
The problem, in fact, is that it is calling `clojure.repl/doc` rather than `cljs.repl/doc`. Back when I first implemented cljs support the `doc` macro didn't exist, but now that it does it should be easily rectifiable.

There is also an issue with it trying to retrieve the stacktrace when that fails, which *should* go away if cider-nrepl is set up correctly.

**Comment by tpope** [comment]
Which is to say, none of that is a blocker. Can we get the history squashed down a bit?

**Comment by venantius** [comment]
Holy dog shit, it all works. Sorry for the extra fluff; didn't have cider-nrepl set up. All signs green here cap'n.

**Comment by siphiuel** [comment]
Phew good to hear that.

**Comment by venantius** [comment]
@siphiuel squash commits?

**Comment by siphiuel** [comment]
Yup, hopefully the commit message is ok (i tried to follow @tpope 's commit message rules).

**Pull request merged**
