### PR TITLE
Support source jumping in ClojureScript code bases

### PR DESCRIPTION
**Pull request by patrickboe**
In response to 'info' messages over nREPL, A REPL consisting of
ClojureScript Rhino REPL + Piggieback + CIDER nREPL provides file paths
as urls (beginning with the 'file:' protocol preamble). Fireplace has
been expecting file paths to be system paths, so attempts to execute
[<C-D> and similar commands would fail.

See
https://github.com/patrickboe/wheel/tree/46df77c1b6d25872b1ac621ba501c6428bc40c80
for an example project affected by this issue. Enter `lein repl` on
the command line, then edit src/main/cljs/wheel/core.cljs in vim.
An attempt to call :Djump wf/myadd will fail without this patch.

This commit adds support for paths expressed as urls, thus making file
jumping possible for projects such as this.

### CODE REVIEW

**Comment by tpope** [comment]
Can you make `s:dir_delim` a function, so that it doesn't get out of date? My preferred name is `s:slash()`.

**Comment by patrickboe** [comment]
sure, done

**Comment by patrickboe** [comment]
oh, darn it, i must have failed to save the change where i renamed dir_delim to slash.  do you want me to just redo this in a new pull request, or submit another commit to this one?

**Comment by tpope** [comment]
I want a single commit.

**Comment by patrickboe** [comment]
okay, i've squashed the three commits together on my feature branch, with an update to the commit message noting the proper SHA for reproducing the original issue..

**Comment by patrickboe** [comment]
amended to rebase onto latest upstream commits

**Pull request merged**
